CoreApp/urls.py
from django.urls import path
from . import views
from GameApp.views import index, game

urlpatterns = [
    path('', views.login_form, name='login_form'),
    path('login_form/', views.login_form, name='login_form'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),

    # learner dashboard
    path('emp_signup/', views.EmployeeSignUpView.as_view(), name='emp_signup'),

    path('employee/', views.home_employee, name='employee'),
    path('emp_interests/', views.EmployeeInterestsView.as_view(), name='emp_interests'),
    path('emp_allquiz/', views.EmployeeAllQuizListView.as_view(), name='emp_allquiz'),
    path('emp_takenquiz/', views.EmployeeTakenQuizListView.as_view(), name='emp_takenquiz'),
    path('quiz/<int:pk>/', views.start_quiz, name='start_quiz'),
    path('emp_books/', views.EmployeeBooksListView.as_view(), name='emp_books'),
    path('emp_notice/', views.EmployeeAnnouncementsListView.as_view(), name='emp_announcements'),
    path('emp_profile/', views.emp_profile, name='emp_profile'),
    path('emp_create_profile/', views.emp_create_profile, name='emp_create_profile'),

    path('play/', index, name='index'),
    path('play/<room_code>', game, name="game"),

    # organizer dashboard
    path('organizer/', views.home_organizer, name='organizer'),

    path('add_quiz/', views.QuizAddView.as_view(), name='add_quiz'),
    path('update_quiz/<int:pk>/', views.QuizUpdateView.as_view(), name='update_quiz'),
    path('quiz/<int:pk>/delete/', views.QuizDeleteView.as_view(), name='delete_quiz'),
    path('edit_quizlist/', views.EditQuizListView.as_view(), name='edit_quizlist'),
    path('quiz/<int:pk>/results/', views.QuizResultsView.as_view(), name='quiz_results'),

    path('add_question/<int:pk>', views.add_question, name='add_question'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/update', views.update_question, name='update_question'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(),
         name='delete_question'),

    path('add_notice/', views.AddNoticeView.as_view(), name='add_notice'),
    path('allnotices/', views.OrganizerAnnouncementsView.as_view(), name='allnotices'),
    
    path('publish_book/', views.publish_book, name='publish_book'),
    path('allbooks/', views.AllBooksList.as_view(), name='allbooks'),
    path('add_book/', views.add_book, name='add_book'),
    path('update_book/<int:pk>', views.update_book, name='update_book'),  

    path('org_profile/', views.org_profile, name='org_profile'),
    path('org_create_profile/', views.org_create_profile, name='org_create_profile'),

    # admin dashboard
    path('owner/', views.home_admin, name='owner'),
    path('reg_organizer/', views.RegisterOrganizerView.as_view(), name='reg_organizer'),
    path('reg_employee/', views.RegisterEmployeeView.as_view(), name='reg_employee'),
    path('reg_interest/', views.register_interest, name='reg_interest'),

    path('adm_add_quiz/', views.AdminQuizAddView.as_view(), name='adm_add_quiz'),
    path('adm_update_quiz/<int:pk>/', views.AdminQuizUpdateView.as_view(), name='adm_update_quiz'),
    path('adm_quiz/<int:pk>/delete/', views.AdminQuizDeleteView.as_view(), name='adm_delete_quiz'),
    path('adm_edit_quizlist/', views.AdminEditQuizListView.as_view(), name='adm_edit_quizlist'),
    path('adm_quiz/<int:pk>/results/', views.AdminQuizResultsView.as_view(), name='adm_quiz_results'),

    path('adm_add_question/<int:pk>', views.adm_add_question, name='adm_add_question'),
    path('adm_quiz/<int:quiz_pk>/question/<int:question_pk>/update', views.adm_update_question, name='adm_update_question'),
    path('adm_quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.AdminQuestionDeleteView.as_view(),
            name='adm_delete_question'),

    path('adm_publish_book/', views.adm_publish_book, name='adm_publish_book'),
    path('adm_allbooks/', views.AdminAllBooksList.as_view(), name='adm_allbooks'),
    path('adm_add_book/', views.adm_add_book, name='adm_add_book'),
    path('adm_update_book/<int:pk>', views.adm_update_book, name='adm_update_book'),  

    path('adm_add_notice/', views.AdminAddNoticeView.as_view(), name='adm_add_notice'),
    path('adm_allnotices/', views.AdminAnnouncementsView.as_view(), name='adm_allnotices'),
    path('adm_delete_notices/', views.AdminDeleteAnnouncementsView.as_view(), name='adm_delete_notices'),
    path('delete_notice/<int:pk>', views.AdminDeleteAnnouncementView.as_view(), name='adm_delete_notice'),

    path('all_users/', views.AllUsersListView.as_view(), name='all_users'),
    path('delete_user/<int:pk>', views.DeleteUserView.as_view(), name='delete_user'),
    path('create_user_form/', views.create_user_form, name='create_user_form'),
    path('create_user/', views.create_user, name='create_user'),

    path('adm_profile/', views.adm_profile, name='adm_profile'),
    path('adm_create_profile/', views.adm_create_profile, name='adm_create_profile'),
]

FunZone/FunZone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CoreApp.urls')),
    path('', include('GameApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FunZone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CoreApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CoreApp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from django.contrib.auth import get_user_model
from embed_video.fields import EmbedVideoField


class User(AbstractUser):
    is_employee = models.BooleanField(default=False)
    is_organizer = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='', default='no-img.jpg', blank=True)
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='')
    email = models.EmailField(default='none@email.com')
    phonenumber = models.CharField(max_length=255, blank=True, null=True)
    birth_date = models.DateField(default='1975-12-12')
    bio = models.TextField(default='')
    city = models.CharField(max_length=255, default='')
    state = models.CharField(max_length=255, default='')
    country = models.CharField(max_length=255, default='')
    favorite_animal = models.CharField(max_length=255, default='')
    hobby = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.user.username


class Announcement(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    posted_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.content)


class Interest(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=7, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Books(models.Model):
    title = models.CharField(max_length=500)
    file = models.FileField(upload_to='', null=True, blank=True)
    cover = models.ImageField(upload_to='', null=True, blank=True)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)


class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Interest, related_name='interested_employees')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class Organizer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    interest = models.ManyToManyField(Interest, related_name="more_locations")


class TakenQuiz(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class EmployeeAnswer(models.Model):
    student = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

CoreApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from django import forms

from CoreApp.models import (Answer, Question, Employee, EmployeeAnswer,
                            Interest, User, Announcement)


class PostForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ('content',)


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput())
    confirm_email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',

        ]

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")

        if email != confirm_email:
            raise forms.ValidationError(
                "Emails must match!"
            )


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class OrganizerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def __init__(self, *args, **kwargs):
        super(OrganizerSignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_organizer = True
        if commit:
            user.save()
        return user


class EmployeeSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Interest.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    def __init__(self, *args, **kwargs):
        super(EmployeeSignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_employee = True
        user.save()
        employee = Employee.objects.create(user=user)
        employee.interests.add(*self.cleaned_data.get('interests'))
        return user


class EmployeeInterestsForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('interests',)
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text',)


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = EmployeeAnswer
        fields = ('answer',)

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')


class EmployeeInterest(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('interests',)
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }

    @transaction.atomic
    def save(self):
        employee = Employee
        employee.interests.add(*self.cleaned_data.get('interests'))
        return employee

CoreApp/templates/dashboard/employee/announcements.html
{% extends 'dashboard/employee/base.html' %}
{% load static %}
  
{% block body %}
<div id="content-wrapper" class="home">
    <div class="homecontainer">
        <div class="card-header pagehead">
            <i class="ri-notification-line"></i>
            List of Announcements Posted
        </div>
        <div class="card-body pagecontainer">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    {{ message }}
                </div>
            {% endfor %}    

            <div class="row">
                {% for chat in object_list %}
                <div class="col-lg-6 noticebox p-3">
                    <div class="card-body">
                        <div class="card-body-icon">
                            <i class="ri-volume-up-fill"></i>
                        </div>
                        <h5 class="notice-title text-white">{{ chat|linebreaks }}</h5>

                        <div class="noticefooter"> 
                            POSTED BY 
                            <span class="details">{{chat.user}}</span> 
                            AT 
                            <span class="details">{{chat.posted_at}}</span> 
                        </div>
                    </div>
                </div>
                {% empty %}
                <h6 class="bg-secondary text-white p-3">NO ANNOUNCEMENTS YET!</h6>
                {% endfor %}
            </div>
            
        </div>
    </div>  
</div>
{% endblock %}

CoreApp/templates/dashboard/employee/base.html
<!DOCTYPE html>
<html lang="en">
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FUN ZONE</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/four/css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard/learner.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand fixed-top">
        <div class="welcome">
            <h3>Hi, {{ user.username }}</h3>
            <p>Many new games waiting to be played</p>
        </div>
        <div class="dropdown ml-auto">
            <a class="nav-link dropdown-toggle arrow" href="#" id="dropdown" role="button" data-toggle="dropdown">
                <img src='{% static "img/pages/user-men.svg" %}' width="50px" height="50px" alt="profile">
            </a>
            <div class="dropdown-menu dropdown-menu-right dropmenu">
                <a class="dropdown-item dropitem" href="{% url 'emp_profile' %}"
                    style="display: flex; align-self: center;"
                >
                    <i class="ri-user-line" style="margin-right: 5px;"></i>{{ user.username }}
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item dropitem" href="" data-toggle="modal" data-target="#logoutModal"
                    style="display: flex; align-self: center;"
                >
                    LOGOUT                   
                    <i class="ri-logout-box-r-line text-primary" style="font-size: larger; margin-left: 10px;"></i>
                </a>
            </div>
        </div>
    </nav> 

    <div id="wrapper">
        <ul class="sidebar navbar-nav"> 
            <li class="nav-item active"> 
                <a class="nav-logo" href="{% url 'employee' %}">
                    <img src='{% static "img/pages/logo.svg" %}'/>
                </a>
            </li> 
            <hr width="80%" class="navdivider""/>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'employee' %}">
                    <div class="sideitem">
                        <div class="icon"><i class="ri-home-5-line"></i></div>
                        <div class="linktext">Employee Dashboard</div>
                    </div>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'emp_interests' %}">
                    <div class="sideitem">
                        <div class="icon"><i class="ri-heart-line"></i></div>
                        <div class="linktext">Update Interests</div>
                    </div>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'emp_allquiz' %}">
                    <div class="sideitem">
                        <div class="icon"><i class="ri-question-answer-line"></i></div>
                        <div class="linktext">Quizzes/Challenges</div>
                    </div>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">
                    <div class="sideitem">
                        <div class="icon"><i class="ri-question-answer-line"></i></div>
                        <div class="linktext">Play Tic-Tac-Toe</div>
                    </div>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'emp_books' %}">
                    <div class="sideitem">
                        <div class="icon"><i class="ri-book-2-line"></i></div>
                        <div class="linktext">Read Books</div>
                    </div>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'emp_announcements' %}">
                    <div class="sideitem">
                        <div class="icon"><i class="ri-notification-line"></i></div>
                        <div class="linktext">Announcements</div>
                    </div>
                </a>
            </li>
        </ul> 
        {% block body %}{% endblock %}
        <!-- /.content-wrapper -->
    </div>
    
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="/logout">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- local scripts -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <script>
        $(".alert-dismissible").fadeTo(2000, 500).slideUp(500, function(){
            $(".alert-dismissible").slideUp(500);
        });
    </script>
</body>

CoreApp/templates/dashboard/employee/create_profile.html
{% extends 'dashboard/employee/base.html' %}
{% load static %}

{% block body %}
<div id="content-wrapper" class="home">
    <div class="homecontainer">
        <div class="pagecontainer">
            {% if users %}
                <div class="card-body bg-white">
                    <center>
                        <a href="{% url 'emp_profile' %}" class="generallink">
                            YOUR PROFILE IS ALREADY CREATED
                        </a>
                    </center>
                </div>
            {% else %}
                <div class="card-header pagehead">
                    <i class="ri-user-line"></i>
                    Create Your Profile
                </div>
                <div class="card-body formbody">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="first_name"
                                            placeholder="First Name" required="required"></div>
                        </div>
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="last_name"
                                            placeholder="Last Name" required="required"></div>
                        </div>
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="phonenumber"
                                            placeholder="Phone Number" required="required"></div>
                        </div>
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="birth_date"
                                            placeholder="Date of Birth" required="required"></div>
                        </div>
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="hobby"
                                                placeholder="Hobby" required="required"></div>
                        </div>
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="city" 
                                            placeholder="City" required="required"></div>
                        </div>
                        <div class="form-group">
                            <div class="col"><input type="text" class="form-control" name="country"
                                            placeholder="Country" required="required"></div>
                        </div>
                        <div class="form-group" id="picfield">
                            <div class="col">
                                <label for="myFile" class="text-white picselect">Choose Profile Picture</label>
                                <input type="file" id="myFile" name="avatar" 
                                    placeholder="Report Attachment"
                                    enctype="multipart/form-data">
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" id="save" class="btn btn-success" href="">SAVE</button>
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

CoreApp/templates/dashboard/employee/header.html
{% load static %}
{% block body %}
<p class="pagesubhead">
    INTERESTS:  
    {% for interest in user.employee.interests.all %} 
        {{ interest.get_html_badge }}
    {% endfor %}
    <a href="{% url 'emp_interests' %}"><small>(Update Interests)</small></a>
</p>

<ul class="nav nav-tabs mb-3">
    <li class="nav-item">
        <b>
            <a class="nav-link {% if active == 'new' %} active text-danger {% endif %} text-success" 
            href="{% url 'emp_allquiz' %}">NEW QUIZZES</a>
        </b>
    </li>
    <li class="nav-item">
        <b>
            <a class="nav-link{% if active == 'taken' %} active text-danger {% endif %} text-success"
            href="{% url 'emp_takenquiz' %}">TAKEN QUIZZES</a>
        </b>
    </li>
</ul>
{% endblock body%}

CoreApp/templates/dashboard/employee/interests_form.html
{% extends 'dashboard/employee/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block body %}
<div id="content-wrapper" class="home">
    <div class="homecontainer" >
        <div class="card-header pagehead">
            <i class="ri-heart-line"></i>
            Please Select Interests
        </div>
        <div class="card-body pagecontainer">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            <form method="post" novalidate class="pageform">
                {% csrf_token %}
                <div class="formdivider">
                    <div class="div1">
                        INTERESTS
                    </div>
                    <div class="div2">
                        {% render_field form.interests %}
                    </div>
                </div>
                <div class="pagebtngrp">
                    <button type="submit" class="btn primarybtn">SAVE</button>
                    <a href="{% url 'employee' %}" class="btn secondarybtn">CANCEL</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

{% block extrascripts %}
<script type="text/javascript">
      $(function () {
          $(".bs-modal").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });
          
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
</script>
{% endblock extrascripts %}

CoreApp/templates/dashboard/employee/take_quiz_form.html
{% extends 'dashboard/employee/base.html' %}

{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block body %}
<div id="content-wrapper" class="home">
  <div class="homecontainer">      
      <div class="card-body pagecontainer">
        <h3 class="numbering">{{ quiz.name }}</h3>

        <div class="timer">
          <div class="label">
            TIME LEFT &nbsp : &nbsp &nbsp   
          </div>
          <div class="progress">
            <div class="progress-bar bg-info" id="timerbar" role="progressbar" aria-valuemin="0" aria-valuemax="20"> 
            </div>
          </div>
        </div>

        <div class="questionbox text-white">
          <p class="lead font-weight-bold"><span class="numbering">{{ counter }})</span>&nbsp{{ question.text }}</p>
          <form method="post" novalidate>
            {% csrf_token %}
            <div class="options" aria-required="false">
              {% render_field form.answer %}
            </div>
            <button type="submit" class="btn btn-success savebutton float-left" id="savebtn">NEXT <i class="ri-arrow-right-line"></i></button>
          </form>
          <p class="float-right" style="margin-top: 45px;">{{ counter }} out of {{ total }} questions</p>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  onload = () => {
    $('#progressbar').css(
      "width", 
      $('#progressbar').data('progress') + "%"
    );

    $('[id^=id_answer_0]').attr(
      "checked",
      true
    );

    c = 0;
  }

  function timerstart(){
    if(c<20){
      c += 1;

      $('#timerbar').css(
        "width", 
        (c * 5)+ "%"
      ).html(c)
    } else {
      savebtn.click();
    }
  }

  intervalTimer = setInterval("timerstart()", 1000);

  let form = document.querySelector( "form" );
  let mydiv = document.querySelector("#id_answer").classList.add("mydiv");
  let firstdiv = document.querySelector(".mydiv > div:first-child").classList.add("firstdiv");
  let firstlabel = document.querySelector(".firstdiv > label").classList.add("checked");
  form.addEventListener( "change", ( evt ) => {
    let trg = evt.target,
      trg_par = trg.parentElement;   
    if ( trg.type === "radio" && trg_par &&
        trg_par.tagName.toLowerCase() === "label" ) {
      let prior = form.querySelector( 'label.checked input[name="' +
                                      trg.name + '"]' );
      if ( prior ) {
        prior.parentElement.classList.remove( "checked" );
      } 
      trg_par.classList.add( "checked" );
    }
  }, false );
</script>
{% endblock body %}